name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-spring-app:$(date +%s)
      
    - name: Run Docker image
      run: docker run -d -p 8080:8080 my-spring-app:$(date +%s)
