name: Docker Image Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker image
      env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository }}
      run: |
        IMAGE_ID=$(echo $REGISTRY/$IMAGE_NAME | tr '[A-Z]' '[a-z]')
        # docker build . --file Dockerfile --tag $IMAGE_ID:${{ github.sha }} -t $IMAGE_ID:latest
        docker buildx build --tag $IMAGE_ID:${{ github.sha }} -t $IMAGE_ID:latest --platform linux/amd64,linux/arm/v7,linux/arm64 .
        docker push --all-tags $IMAGE_ID
